name: CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0 # Or your preferred LTS version

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Run Prettier (style check)
        run: npm run format # Or npx prettier --check . if you only want to check, not reformat


      # - name: Run unit tests  # Uncomment and configure when you have tests
      #   run: npm test
