name: EAS Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    uses: ./.github/workflows/setup-node-expo.yml  # Reusable workflow for setup
    with:
      node-version: '20.x'
      expo-version: 'latest'
      eas-version: 'latest'

    # No need to repeat steps here, all steps are handled by the reusable workflow
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    # Custom steps for the build process:
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Build Android app
        run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release-${{ env.APP_VERSION }}.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ env.APP_VERSION }}
          path: ${{ github.workspace }}/app-release-${{ env.APP_VERSION }}.apk