name: Release

on:
  push:
    branches:
      - master
      - release/*

jobs:
  publish:
    uses: ./.github/workflows/setup-node-expo.yml  # Reusable workflow
    with:
      node-version: '20.x'
      expo-version: 'latest'
      eas-version: 'latest'

    steps:
      - name: Publish update to Expo
        run: npx eas update --branch production --message "Automated update from GitHub Actions"
