name: EAS Build and Release

on:
  push:
    branches:
      - master
      - develop
      - release/*

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Set up Expo and EAS
      - name: Set up Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Set APP_VERSION from package.json
      - name: Get App Version
        run: |
          APP_VERSION=$(node -p "require('./package.json').version")
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          
  build:
    needs: setup  # This job will run after the setup job completes
    runs-on: ubuntu-latest
    steps:
      # Set up JDK 17 for Android build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Set up Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Cache Gradle dependencies for faster builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      # Build Android app with EAS
      - name: Build Android app
        run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release-${{ env.APP_VERSION }}.apk

      # Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ env.APP_VERSION }}
          path: ${{ github.workspace }}/app-release-${{ env.APP_VERSION }}.apk

  release:
    needs: build  # This job runs after the build job completes
    runs-on: ubuntu-latest
    steps:
      # Checkout the code again in case it's needed for Expo update
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js, Expo, and install dependencies
      - name: Set up Node.js, Expo, and Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Set up Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Install dependencies again in case the environment changed
      - name: Install dependencies
        run: npm ci

      # Publish the app update to Expo
      - name: Publish update to Expo
        run: npx eas update --branch production --message "Automated update from GitHub Actions"