name: Release

on:
  push:
    branches:
      - master
      - release/*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js, Expo, and Install Dependencies
        uses: ./.github/workflows/setup-node-expo.yml  # Reusable workflow for setup

      - name: Publish update to Expo
        run: npx eas update --branch production --message "Automated update from GitHub Actions"