name: EAS Build and Release

on:
  push:
    branches:
      - master # Trigger workflow on pushes to master (production branch)
      - develop # Trigger workflow on pushes to develop (staging/development branch)
      - release/* # Trigger workflow on pushes to branches starting with "release/" (for release candidates)

jobs:
  setup:
    name: Setup Environment and Get App Version
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.get_app_version.outputs.app_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Use a specific LTS version (e.g., 20.10.0)

      - name: Install project dependencies
        run: npm ci

      - name: Get App Version from package.json
        id: get_app_version
        shell: bash
        run: |
          APP_VERSION=$(node -p "require('./package.json').version")
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "App Version: $APP_VERSION"

  build-android:
    name: Build Android App
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Install EAS CLI
        run: npm install -g eas-cli # Or use a local install with npx

      - name: Set up Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest # Pin Expo SDK version for consistency
          eas-version: latest # Pin EAS CLI version for consistency
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install project dependencies
        run: npm ci # Review if this is needed after Expo setup

      - name: Build Android app with EAS
        run: |
          eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release-${{ needs.setup.outputs.app_version }}.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ needs.setup.outputs.app_version }}
          path: ${{ github.workspace }}/app-release-${{ needs.setup.outputs.app_version }}.apk

  release:
    name: Release and Publish to Expo
    needs: build-android
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Only run on pushes to master
    permissions:
      contents: write # Grant write access for creating releases and tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for semantic-release

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Only if publishing to npm
        run: npx semantic-release

      - name: Publish update to Expo (if semantic-release didn't create a release)
        if: steps.semantic_release.outcome != 'success' # Check if semantic-release created a release
        run: npx eas update --branch production --message "Automated update from GitHub Actions - v${{ needs.setup.outputs.app_version }}" # Or eas submit for production release